# docker-compose up -d (muss im Folder dieser datei sein und die datei muss docker-compose.yaml heißen)
version: '3'
services:
  postgredb:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
    postgresdata: